name: Deploy Web App to Netlify

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: apps/web
        run: npm install

      - name: Build the web app
        working-directory: apps/web
        run: npm run build

      - name: Deploy via Netlify CLI
        working-directory: apps/web
        run: |
          npm install -g netlify-cli
          netlify deploy --build --prod \
            --dir=.next \
            --functions=netlify/functions \ 
            --site=$NETLIFY_SITE_ID_WEB \
            --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_WEB }}
